### ISSUE TITLE
Restyle <kbd>

### ISSUE THREAD

**Issue by dascritch** [dascritch/cpu-15#40]
Re use dascritch.net ? 

```css
kbd {
    background:none repeat scroll 0 0 #eee;
    border-color:#ccc #aaa #888 #bbb;
    border-style:solid;
    border-width:2px 3px 3px 2px;
    padding:0 2px;color:#000000;
    display:inline-block;
    min-width:15px;
    position:relative;
    text-align:center;
   text-shadow:none;
   white-space:nowrap;
    box-shadow:0 0 5px rgba(0,0,0,0.5);
}
```
