### ISSUE TITLE
Resstyle <q>

### ISSUE THREAD

**Issue by dascritch** [dascritch/cpu-15#41]
we are missing quotes, no need to italicize.

from dsn13 dascritch.net
```css
blockquote,q {
   font-style:italic
}

blockquote em,q em{
   font-style:normal
}

q,cite,quote,blockquote { 
    quotes:"\201c" "\201d" "\00ab\00a0" "\00a0\00bb"
}
```
